# Generated by Django 3.1.7 on 2021-03-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100)),
                ('article', models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_set_name', models.CharField(max_length=100)),
                ('question_1', models.CharField(blank=True, default='', max_length=300)),
                ('A1', models.CharField(blank=True, default='', max_length=200)),
                ('B1', models.CharField(blank=True, default='', max_length=200)),
                ('C1', models.CharField(blank=True, default='', max_length=200)),
                ('D1', models.CharField(blank=True, default='', max_length=200)),
                ('answer_1', models.IntegerField(blank=True, default=0)),
                ('question_2', models.CharField(blank=True, default='', max_length=300)),
                ('A2', models.CharField(blank=True, default='', max_length=200)),
                ('B2', models.CharField(blank=True, default='', max_length=200)),
                ('C2', models.CharField(blank=True, default='', max_length=200)),
                ('D2', models.CharField(blank=True, default='', max_length=200)),
                ('answer_2', models.IntegerField(blank=True, default=0)),
                ('question_3', models.CharField(blank=True, default='', max_length=300)),
                ('A3', models.CharField(blank=True, default='', max_length=200)),
                ('B3', models.CharField(blank=True, default='', max_length=200)),
                ('C3', models.CharField(blank=True, default='', max_length=200)),
                ('D3', models.CharField(blank=True, default='', max_length=200)),
                ('answer_3', models.IntegerField(blank=True, default=0)),
                ('question_4', models.CharField(blank=True, default='', max_length=300)),
                ('A4', models.CharField(blank=True, default='', max_length=200)),
                ('B4', models.CharField(blank=True, default='', max_length=200)),
                ('C4', models.CharField(blank=True, default='', max_length=200)),
                ('D4', models.CharField(blank=True, default='', max_length=200)),
                ('answer_4', models.IntegerField(blank=True, default=0)),
                ('question_5', models.CharField(blank=True, default='', max_length=300)),
                ('A5', models.CharField(blank=True, default='', max_length=200)),
                ('B5', models.CharField(blank=True, default='', max_length=200)),
                ('C5', models.CharField(blank=True, default='', max_length=200)),
                ('D5', models.CharField(blank=True, default='', max_length=200)),
                ('answer_5', models.IntegerField(blank=True, default=0)),
                ('question_6', models.CharField(blank=True, default='', max_length=300)),
                ('A6', models.CharField(blank=True, default='', max_length=200)),
                ('B6', models.CharField(blank=True, default='', max_length=200)),
                ('C6', models.CharField(blank=True, default='', max_length=200)),
                ('D6', models.CharField(blank=True, max_length=200)),
                ('answer_6', models.IntegerField(blank=True, default=0)),
                ('question_7', models.CharField(blank=True, default='', max_length=300)),
                ('A7', models.CharField(blank=True, default='', max_length=200)),
                ('B7', models.CharField(blank=True, default='', max_length=200)),
                ('C7', models.CharField(blank=True, default='', max_length=200)),
                ('D7', models.CharField(blank=True, default='', max_length=200)),
                ('answer_7', models.IntegerField(blank=True, default=0)),
                ('question_8', models.CharField(blank=True, default='', max_length=300)),
                ('A8', models.CharField(blank=True, default='', max_length=200)),
                ('B8', models.CharField(blank=True, default='', max_length=200)),
                ('C8', models.CharField(blank=True, default='', max_length=200)),
                ('D8', models.CharField(blank=True, default='', max_length=200)),
                ('answer_8', models.IntegerField(blank=True, default=0)),
                ('question_9', models.CharField(blank=True, default='', max_length=300)),
                ('A9', models.CharField(blank=True, default='', max_length=200)),
                ('B9', models.CharField(blank=True, default='', max_length=200)),
                ('C9', models.CharField(blank=True, default='', max_length=200)),
                ('D9', models.CharField(blank=True, default='', max_length=200)),
                ('answer_9', models.IntegerField(blank=True, default=0)),
                ('question_10', models.CharField(blank=True, default='', max_length=300)),
                ('A10', models.CharField(blank=True, default='', max_length=200)),
                ('B10', models.CharField(blank=True, default='', max_length=200)),
                ('C10', models.CharField(blank=True, default='', max_length=200)),
                ('D10', models.CharField(blank=True, default='', max_length=200)),
                ('answer_10', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Practice_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(default=0)),
                ('sub_code', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=100)),
                ('all_articles', models.ManyToManyField(blank=True, to='coursesetup.Articles')),
                ('all_practice', models.ManyToManyField(blank=True, to='coursesetup.Practice')),
            ],
        ),
        migrations.CreateModel(
            name='CreateCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('all_modules', models.ManyToManyField(to='coursesetup.Modules')),
            ],
        ),
    ]
