# Generated by Django 3.1.7 on 2021-03-14 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesetup', '0002_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='all_videos',
            field=models.ManyToManyField(blank=True, to='coursesetup.Videos'),
        ),
    ]
