# Generated by Django 3.1.7 on 2021-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesetup', '0003_modules_all_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcourse',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='createcourse',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='modules',
            name='isFree',
            field=models.BooleanField(default=False),
        ),
    ]
