# Generated by Django 3.1.7 on 2021-03-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesetup', '0004_auto_20210317_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
