# Generated by Django 3.1.7 on 2021-03-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesetup', '0005_videos_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='isFree',
        ),
        migrations.AddField(
            model_name='createcourse',
            name='isFree',
            field=models.BooleanField(default=False),
        ),
    ]
