# Generated by Django 3.1.7 on 2021-04-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursesetup', '0006_auto_20210319_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=56)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='createcourse',
            name='resources',
            field=models.FileField(default=1, upload_to='resourses/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createcourse',
            name='image',
            field=models.ImageField(upload_to='courseimages/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videos',
            field=models.FileField(upload_to='videos/'),
        ),
    ]
